# Sidebar navigation

- label: 'Introduction'
  link: '/'
- label: Walkthrough
  items:
    - label: 'Installation'
      link: '/walkthrough/installation'
    - label: 'Basic usage'
      link: '/walkthrough/basic-usage'
    - label: 'Use plugin'
      link: '/walkthrough/use-plugin'
    - label: 'Validation'
      link: '/walkthrough/validation'
- label: Guide
  items:
    - label: 'Schema'
      link: '/guide/schema'
    - label: 'Custom field'
      link: '/guide/custom-field'
    - label: 'Custom validator'
      link: '/guide/custom-validator'
    - label: 'Reset form'
      link: '/guide/reset-form'

- label: Api
  items:
    - label: 'useForm'
      link: '/api/use-form'
    - label: 'useField'
      link: '/api/use-field'
    - label: 'useFormContext'
      link: '/api/use-form-context'
    - label: 'useFormState'
      link: '/api/use-form-state'
- label: More
  items:
    - label: FAQ
      link: /faq
    - label: 'Github'
      link: https://github.com/jpedroschmitz/rocketdocs
